SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SecondPhaseSetPieces](
	[ID] [int] IDENTITY(1,1) NOT NULL,
    [game_id] [nvarchar](50) NULL,

 CONSTRAINT [PK_SecondPhaseSetPieces] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
