CREATE TYPE [dbo].[OptaCoreStatsType] AS TABLE(
	[Competition ID] [nchar](10) NULL,
	[Competition Name] [nvarchar](50) NULL,
	[Date] [date] NULL,
	[Game ID] [nchar](10) NULL,
	[Home/Away] [nchar](10) NULL,
	[Opposition Team Formation] [nchar](10) NULL,
	[Opposition Team Formation ID] [int] NULL,
	[Opposition Team ID] [nchar](10) NULL,
	[Opposition Team Name] [nvarchar](50) NULL,
	[Player ID] [nchar](10) NULL,
	[Player Name] [nvarchar](50) NULL,
	[Position ID] [int] NULL,
	[Season ID] [nchar](10) NULL,
	[Season Name] [nvarchar](50) NULL,
	[Start] [bit] NULL,
	[Substitute Off] [bit] NULL,
	[Substitute On] [bit] NULL,
	[Team Formation] [nchar](10) NULL,
	[Team Formation ID] [int] NULL,
	[Team ID] [nchar](10) NULL,
	[Team Name] [nvarchar](50) NULL,
    [Sent Off] [bit] NULL,
    [Retired] [bit] NULL,
	[Time Played] [float] NULL,
	[Time In Possession] [float] NULL,
	[Time Out Of Possession] [float] NULL,
    [Time Played Calculated From Tracking Data] [nvarchar](50) NULL
)
GO
